-- DROP TABLE IF EXISTS Texts;
-- DROP TABLE IF EXISTS Lang;

-- CREATE TABLE Texts (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     content TEXT
-- );

-- CREATE TABLE Lang (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     language TEXT
-- );

DROP TABLE IF EXISTS Urls;

CREATE TABLE Urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_url TEXT NOT NULL,
    hashed_url TEXT NOT NULL
    -- clicks INTEGER NOT NULL DEFAULT 0
);